"""Emit Artisan RelicToolPremadeLists definitions from gen_tool_materials.py (stdout: C# rows)."""
import re
from pathlib import Path

text = Path(__file__).with_name("gen_tool_materials.py").read_text(encoding="utf-8")
C = ["CRP", "BSM", "ARM", "GSM", "LTW", "WVR", "ALC", "CUL"]
JOB = {
    "CRP": "Carpenter",
    "BSM": "Blacksmith",
    "ARM": "Armorer",
    "GSM": "Goldsmith",
    "LTW": "Leatherworker",
    "WVR": "Weaver",
    "ALC": "Alchemist",
    "CUL": "Culinarian",
}


def extract_brace_block(s, start):
    depth = 0
    for i in range(start, len(s)):
        if s[i] == "{":
            depth += 1
        elif s[i] == "}":
            depth -= 1
            if depth == 0:
                return s[start : i + 1]
    raise ValueError("unbalanced braces")


def parse_crafter(step, cnt, block):
    out = []
    for cls in C:
        pat = rf'"{cls}":\(".*?",\[.*?\],"([^"]+)"\)'
        m = re.search(pat, block, re.S)
        if m:
            out.append((step, cls, m.group(1), cnt))
    return out


def parse_craft_tree(step, cnt, block):
    out = []
    for cls in C:
        pat = rf'"{cls}":\s*\{{[^}}]*"collectable":\s*"([^"]+)"'
        m = re.search(pat, block)
        if m:
            out.append((step, cls, m.group(1), cnt))
    return out


entries = []
for m in re.finditer(r'crafter\("([^"]+)",(\d+),\d+,\{', text):
    step, cnt = m.group(1), int(m.group(2))
    block = extract_brace_block(text, m.end() - 1)
    entries.extend(parse_crafter(step, cnt, block))

for m in re.finditer(r'craft_tree\("([^"]+)",\s*(\d+),\s*\{', text):
    step, cnt = m.group(1), int(m.group(2))
    block = extract_brace_block(text, m.end() - 1)
    entries.extend(parse_craft_tree(step, cnt, block))

STEP_ORDER = [
    "Skysteel +1",
    "Dragonsung",
    "Augmented Dragonsung",
    "Skysung",
    "Skybuilders'",
    "Augmented",
    "Crystalline",
    "Chora-Zoi's",
    "Brilliant",
    "Vrandtic",
    "Lodestar",
]
step_ord = {s: i + 1 for i, s in enumerate(STEP_ORDER)}

lines = [
    "// Generated by RelicTracker data/gen_artisan_relic_lists.py — do not edit by hand.",
    "namespace Artisan.CraftingLists;",
    "",
    "internal static partial class RelicToolPremadeLists",
    "{",
    "    private static readonly RelicToolPremadeEntry[] Definitions =",
    "[",
]
for step, cls, coll, cnt in entries:
    lid = 900_000 + step_ord[step] * 10 + C.index(cls)
    name = "Relic Tool — {} — {}".format(step, JOB[cls])
    coll_esc = coll.replace("\\", "\\\\").replace('"', '\\"')
    lines.append('        new({}, "{}", {}, "{}", {}),'.format(lid, name, cnt, coll_esc, C.index(cls)))
lines.extend([
    "    ];",
    "    // {} lists".format(len(entries)),
    "}",
])
body = "\n".join(lines) + "\n"
print(body)
out_path = Path(__file__).resolve().parents[1].parent / "Artisan" / "Artisan" / "CraftingList" / "RelicToolPremadeLists.Definitions.cs"
if out_path.parent.exists():
    out_path.write_text(body, encoding="utf-8")
    print("Wrote {}".format(out_path), file=__import__("sys").stderr)
