"""Emit Artisan RelicToolPremadeLists definitions from gen_tool_materials.py (stdout: C# rows)."""
import re
import sys
from pathlib import Path

from item_lookup import load_item_index

text = Path(__file__).with_name("gen_tool_materials.py").read_text(encoding="utf-8")
C = ["CRP", "BSM", "ARM", "GSM", "LTW", "WVR", "ALC", "CUL"]

STEP_ENUM = {
    "Skysteel +1": "SkysteelPlus1",
    "Dragonsung": "Dragonsung",
    "Augmented Dragonsung": "AugmentedDragonsung",
    "Skysung": "Skysung",
    "Skybuilders'": "Skybuilders",
    "Augmented": "Augmented",
    "Crystalline": "Crystalline",
    "Chora-Zoi's": "ChoraZois",
    "Brilliant": "Brilliant",
    "Vrandtic": "Vrandtic",
    "Lodestar": "Lodestar",
}

STEP_ORDER = list(STEP_ENUM.keys())


def extract_brace_block(s, start):
    depth = 0
    for i in range(start, len(s)):
        if s[i] == "{":
            depth += 1
        elif s[i] == "}":
            depth -= 1
            if depth == 0:
                return s[start : i + 1]
    raise ValueError("unbalanced braces")


def parse_crafter(step, cnt, block):
    out = []
    for cls in C:
        pat = rf'"{cls}":\(".*?",\[.*?\],"([^"]+)"\)'
        m = re.search(pat, block, re.S)
        if m:
            out.append((step, cls, m.group(1), cnt))
    return out


def parse_craft_tree(step, cnt, block):
    out = []
    for cls in C:
        pat = rf'"{cls}":\s*\{{[^}}]*"collectable":\s*"([^"]+)"'
        m = re.search(pat, block)
        if m:
            out.append((step, cls, m.group(1), cnt))
    return out


entries = []
for m in re.finditer(r'crafter\("([^"]+)",(\d+),\d+,\{', text):
    step, cnt = m.group(1), int(m.group(2))
    block = extract_brace_block(text, m.end() - 1)
    entries.extend(parse_crafter(step, cnt, block))

for m in re.finditer(r'craft_tree\("([^"]+)",\s*(\d+),\s*\{', text):
    step, cnt = m.group(1), int(m.group(2))
    block = extract_brace_block(text, m.end() - 1)
    entries.extend(parse_craft_tree(step, cnt, block))

index = load_item_index(Path(__file__).with_name("cache") / "Item.csv")

lines = [
    "// Generated by RelicTracker data/gen_artisan_relic_lists.py — do not edit by hand.",
    "namespace Artisan.CraftingLists;",
    "",
    "internal static partial class RelicToolPremadeLists",
    "{",
    "    // (step, quantity, itemId, craftType) — list ID is derived.",
    "    private static readonly RelicToolPremadeEntry[] Definitions =",
    "    [",
]

last_step = None
for step, cls, coll, cnt in entries:
    if step not in STEP_ENUM:
        raise SystemExit(f"Unknown Artisan relic step: {step!r}")
    if step != last_step:
        lines.append(f"        // {step}")
        last_step = step
    item_id = index.resolve(coll)
    enum_name = STEP_ENUM[step]
    craft_type = C.index(cls)
    lines.append(f"        new(RelicToolStep.{enum_name}, {cnt}, {item_id}, {craft_type}),")

lines.extend(
    [
        "    ];",
        f"    // {len(entries)} lists",
        "}",
    ]
)
body = "\n".join(lines) + "\n"
print(body)
out_path = Path(__file__).resolve().parents[1].parent / "Artisan" / "Artisan" / "CraftingList" / "RelicToolPremadeLists.Definitions.cs"
if out_path.parent.exists():
    out_path.write_text(body, encoding="utf-8")
    print(f"Wrote {out_path}", file=sys.stderr)
